### ISSUE TITLE
Error al intentar ejecutar la imagen del proyecto gabrielstan/gestion-tfg

### ISSUE THREAD

**Issue by dbo1001** [dbo1001/Gestor-TFG-2016#19]

**Comment by dbo1001** [comment]
Para probar el proyecto [gestion-tfg ](https://github.com/gabriel-stan/gestion-tfg) se ha descargado la imagen de [docker](https://hub.docker.com/r/gabrielstan/gestion-tfg/) y al proceder a ejecutar dicha imagen da error.
Se ha seguido lo indicado en la propia documentación del proyecto: https://github.com/gabriel-stan/gestion-tfg/blob/master/docs/README-contenerizacion.md

**Comment by dbo1001** [comment]
Se ha descargado la imagen a través del comando _**sudo docker pull gabrielstan/gestion-tfg:latest**_  y, como se puede ver en la siguiente imagen, la imagen se ha descargado correctamente:

![Captura de pantalla de 2021-01-19 14-26-57](https://user-images.githubusercontent.com/44766510/105040958-bd0d6a80-5a62-11eb-9e6d-8854a99bfaa5.png)

Pero, al intentar crear y arrancar el contenedor a partir de esa imagen da el siguiente error:
![Captura de pantalla de 2021-01-19 14-25-49](https://user-images.githubusercontent.com/44766510/105041894-d95dd700-5a63-11eb-9a8f-dfd47fb938c3.png)

**Comment by dbo1001** [comment]
Parece ser un error al importar el run_gunicorn.sh que es donde se realiza la importación del django.core.management.

**Comment by alvarag** [comment]
Entiendo que la ejecución:

```
docker run gabrielstan/gestion-tfg ....
```

Es la que el creador propone para poderlo ejecutar, ¿verdad?

**Comment by alvarag** [comment]
La otra opción que se me ocurre es la de tratar de lanzarlo con fabric:
https://github.com/gabriel-stan/gestion-tfg/blob/master/docs/README-fabric.md

Y si ninguna de las opciones vemos que son viables, habrá que poner en la memoria que no hubo manera de ejecutarlo.

**Comment by dbo1001** [comment]
En la documentación del proyecto viene lo siguiente:

- Hay disponible una imagen actualizada constantemente desde el repositorio de Github a través de un automated build. En el repositorio también hay disponible una versión de la imagen según el estado de desarrollo del proyecto (development).

- Para probar la aplicación en un entorno local basta con ejecutar el comando make install-docker, el cual se asegurará de tener instalado Docker en el sistema, descargará la imagen de DockerHub y ejecutará la aplicación en un contenedor.
- Una vez ejecutada, la aplicación se puede acceder a través del enlace <ip-contenedor>:8000.

En cuanto al comando_**make install-docker**_ no se muy bien a lo que se refiere, porque he probado a ponerlo y me dice que ese comando no existe y, he buscado por internet y en ningún sitio me viene que las imágenes se ejecutan así. Por eso lo he hecho con el comando _**docker run gabrielstan/gestion-tfg**_ que es como se supone que se ejecutan.

**Comment by dbo1001** [comment]
Voy a probar a lanzarlo con fabric como has dicho.

**Comment by alvarag** [comment]
Creo que se refiere a utilizar _make_ el comando de construcción habitual en _C_. Creo que en 1º del Grado os lo explica Carlos Pardo.

https://www.gnu.org/software/make/

Prueba a instalarte make y hacer el _make install-docker_

**Comment by dbo1001** [comment]
Si, le instalé pero no me iba. Lo voy a volver a probar de todas formas por si acaso lo instale mal o hice algo mal. 

Muchas gracias.
